# Generated by Django 4.1.1 on 2023-03-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_image_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='website',
            field=models.CharField(default='Website name', max_length=100),
        ),
    ]
